In [1]:
"""
Landon Buell
Marek Petrik
CS 750.01
5 Feb 2020
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


## Problem 1 [30%]
#### This problem examines the use and assumptions of Linear Discrimiant Analysis (LDA) and Quadratic Discrimiant Analysis (QDA). We will be using the dataset Default from ISLR. 

I loaded the datset into R, and the rewrote it as a CSV to use in python!

In [2]:
# load in data from CSV and make all numeric
default = pd.read_csv("Default.txt",sep=",",header=0,usecols=[1,2,3,4])

default = default.replace("No",0)
default = default.replace("Yes",1)
default = default.astype(float)

default.head()

default  student      balance        income
0      0.0      0.0   729.526495  44361.625074
1      0.0      1.0   817.180407  12106.134700
2      0.0      0.0  1073.549164  31767.138947
3      0.0      0.0   529.250605  35704.493935
4      0.0      0.0   785.655883  38463.495879

1. Split the data into a training set (70%) and a test set (30%). Then compare the classification error of LDA, QDA, and logistic regression when predicting default as a function of features of your choice. Which method appears to work best? 

In [5]:
from sklearn.model_selection import train_test_split

# split data set into train & test
y = default['default'].astype(int)
X = default[['student','balance','income']]

xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3)

# Create linear disc. Classifier instance
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
LDA_CLF = LDA()
LDA_CLF.fit(xtrain,ytrain)
LDA_pred = LDA_CLF.predict(xtest)

# Create Quadratic Disc. Classifier instance
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
QDA_CLF = QDA()
QDA_CLF.fit(xtrain,ytrain)
QDA_pred = QDA_CLF.predict(xtest)

# Create Logstic Regression 
from sklearn.linear_model import LogisticRegression as LRC
LRC_CLF = LRC()
LRC_CLF.fit(xtrain,ytrain)
LRC_pred = LRC_CLF.predict(xtest)

from sklearn.metrics import accuracy_score 
LDA_score = accuracy_score(ytest,LDA_pred)
QDA_score = accuracy_score(ytest,QDA_pred)
LRC_score = accuracy_score(ytest,LRC_pred)


print("Linear Disc. Analysis Classification Error:",LDA_score)
print("Quadratic Disc. Analysis Classification Error:",QDA_score)
print("Logistic Regression Classification Error:",LRC_score)

Linear Disc. Analysis Classification Error: 0.9756666666666667
Quadratic Disc. Analysis Classification Error: 0.9753333333333334
Logistic Regression Classification Error: 0.9706666666666667


C:\Users\Landon\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


2. Report the confusion table for each classification method. Make sure to label which dimension is the predicted class and which one is the true class. What do you observe? 

In [12]:
from sklearn.metrics import confusion_matrix

print("Linear Disc. Analysis Confusion Matrix:")
LDA_confmat = confusion_matrix(ytest,LDA_pred)
print(LDA_confmat)

print("Quadratic Disc. Analysis Confusion Matrix:")
QDA_confmat = confusion_matrix(ytest,QDA_pred)
print(QDA_confmat)

print("Logisitc Regression Confusion Matrix:")
LRC_confmat = confusion_matrix(ytest,LRC_pred)
print(LRC_confmat)


Linear Disc. Analysis Confusion Matrix:
[[2905    8]
 [  65   22]]
Quadratic Disc. Analysis Confusion Matrix:
[[2902   11]
 [  63   24]]
Logisitc Regression Confusion Matrix:
[[2912    1]
 [  87    0]]


Each confusion matrix has a string entry at index (1,1) - the True Positive entry. This means that It is excellent at correctly identifying those who belong into class '0': i.e. those who will NOT default on their loans. However, entry (2,2) seems to be very weak, this means that each method is poor at identifying any instance in class "1": those who did default on their loans. Furthermore, the entry (2,1) is generally much stronger, indicating that that model predicted the person would not default, even though they did. We usually want a confusion matrix with a strong main diagonal and weaker off-diagonals. These matricies do not grant us that so well.

3. Are the LDA assumptions satisfied when predicting default as a function of balance only (i.e default ~ balance)? You can use qqnorm and qqline to examine whether the conditional class distributions are normally distributed. Also examine standard deviations of the class distributions. Are the QDA assumptions satisfied? 

4. Would you ever want to use LDA in place of QDA even when you suspect that some of the assumptions are violated (e.g. different conditional standard deviations) for LDA? Hint: Check out TidyVerse for a collection of packages that can help with data manipulation. And see the Rstudio cheatsheets for a convenient and concise reference to the methods. This is entirely optional!

## Problem 2 [30%] 
#### Using the MNIST dataset, fit classification models in order to predict the digit 1 (vs all others).

1. Compare the classification error for each one of these methods:

In [14]:
# load in MNIST dataset
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784',version=1)
print(mnist.keys())
X,y = mnist['data'],mnist['target'].astype(np.uint8)

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'details', 'categories', 'url'])


In [15]:
# split into train-test sets
xtrain,xtest,ytrain,ytest = X[:60000],X[60000:],y[:10000],y[10000:]

2. Logistic regression

3. K-NN (with 2 reasonable choices of k)

4. LDA