In [11]:
"""
Landon Buell
21 April 2020
"""

import numpy as np

# total layers (hidden + input + output)
N_layers = 10

for l in range (N_layers-1,0,-1):
    print("Layer:",l)


Layer: 9
Layer: 8
Layer: 7
Layer: 6
Layer: 5
Layer: 4
Layer: 3
Layer: 2
Layer: 1


In [21]:
dx = np.array([20.18476685, 26.65055091, 24.46695741])
Ac = np.array([3.2768324,  2.81559469, 3.02497353, 7.63424908, 5.79767725, 3.69076313])

In [13]:
dx.transpose() @ Ac

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [15]:
dy = np.array([dx])
dy

array([[20.18476685, 26.65055091, 24.46695741]])

In [17]:
dy.transpose()

array([[20.18476685],
       [26.65055091],
       [24.46695741]])

In [18]:
dy @ Ac

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 3)

In [19]:
dy.shape

(1, 3)

In [20]:
Ac.shape

(6,)

In [24]:
result = dx.reshape(-1,1) @ Ac.reshape(1,-1)
result

array([[ 66.142098  ,  56.83212236,  61.05838543, 154.09553775,
        117.02476356,  74.49719328],
       [ 87.3293887 ,  75.03714963,  80.61721106, 203.45694377,
        154.51129271,  98.36087069],
       [ 80.17411877,  68.88903536,  74.01189852, 186.7868471 ,
        141.85152235,  90.30174431]])

In [25]:
result.shape

(3, 6)